language: ruby
rvm:
  - 2.4.1
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-dupe --allow-ssl --allow-redirect --set-timeout 5 | grep -Ev "\s*?[0-9]{1,4}\.\s*?http"

name: Fork Sync
  uses: TG908/fork-sync@v1.1.7
